import pandas as pd
df = pd.read_csv("data/verify/judgment_scan_zenchi_2026-08-22/suspects.tsv", sep="\t")
print("総件数:", len(df))
print("\n--- detector別 ---")
print(df["detector"].value_counts())
print("\n--- stage別 ---")
print(df["stage"].value_counts())
print("\n--- detector x stage ---")
print(df.groupby(["detector","stage"]).size())
print("\n--- game_idx別件数 (上位20) ---")
print(df["game_idx"].value_counts().head(20))
print("\n--- game_idx別件数 (下位20、少ない側) ---")
print(df["game_idx"].value_counts().tail(20))
print("\n--- t_sec分布 (min/max) ---")
print(df["t_sec"].min(), df["t_sec"].max())
print("\n--- game_idx=0 の t_sec範囲 ---")
g0 = df[df["game_idx"]==0]
print(len(g0), g0["t_sec"].min() if len(g0) else None, g0["t_sec"].max() if len(g0) else None)
print("\n--- game_idx>=1 の件数 ---")
print(len(df[df["game_idx"]>=1]))
print("\n--- game_idxごとのユニーク数 ---")
print(df["game_idx"].nunique(), "個のgame_idxに疑義あり (総game_idx数と比較)")
